// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieGame.Infrastructure;

#nullable disable

namespace MovieGame.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20240611105201_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MovieGame.MODEL.MovieeGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReleaseYear")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieGames");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Publisher = "Example Publisher",
                            ReleaseYear = 2020,
                            Title = "Example Game"
                        },
                        new
                        {
                            Id = 2,
                            Publisher = "Second Publisher",
                            ReleaseYear = 2021,
                            Title = "Second Game"
                        },
                        new
                        {
                            Id = 3,
                            Publisher = "Third Publisher",
                            ReleaseYear = 2022,
                            Title = "Third Game"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
